sudo: true
branches:
  only:
  - master
language: node_js
node_js:
- '12'
before_install:
- export TZ=Asia/Taipei
install:
- npm install
before_script: 
script:
- npm run check
- "./deploy.sh"
env:
  global:
  - secure: GNYhSCMnODUkGfhLey84qah54nFAYPUGan/skga/UOH6ZVKxlWm5m8PAcmKVhMdibCN0faPc8kEomHw0UEoYb900XEg884wqESwdxXBqlNxpcUmxvGlV0/FylHJ0Mv24hJaXiUwYVWEyctrsgV7PO35F4YdoMqFEMafpgT5iYmC0xOUMs+USoHHl8l3tukn/gtnvNmuh8oELbD/fYkyJdJ5uI5R3uMzQa6Jeqo9LWqQf7laHE8FP9PsxhtSEtkR1jr+uZlioVIoY8pc4aCmNJ8bWkYFuBvsJzfOmsXqFfn/9iz24KSoPoS5Ycx3lEu43ltdb+hAIGviDAw4pRpI2sBuKGO9S1hncL3agq3X1KpxZw7RQf+AD5yPuflR9k3isoiYCbPpOu8E1qo0Q9vWi6EWQlq3kz/yObQ/xY8t2/xQBNh6pjA2ltttrMpRUP0ViXwjhQBhpPFG04yTL1aTYJOJsc5ouYL/N/0h0QpkwdxmSxAc8usvSVe6bDJbPhq485GVoLXlJ3E+sc0uaxgAb8G6/arCgcDa1JCDUF0UXE4jwvnm7tp+aPs/FKo99rIH4/zEmEG+nCxrCxMdWWTOu/6OF+vwpLR7tf2/pSK8W4bJWf++gat1Fd/7SOrgjtH9dVVd+NE8O6HB1z7M0L2efgR9R3aspRTttByynLxVAisE=
